### ISSUE TITLE
Why interface IRepository in Revo.Infrastructure ? 

### ISSUE THREAD

**Issue by RustamGulamov** [revoframework/Revo#21]
Why interface IRepository in Revo.Infrastructure ?
this is contrary to hexagonal or n-layered architecture. 
The Application layer should not depend from Infrastructure

**Comment by martinzima** [comment]
Hello RustamGulamov,

No, not really - in hexagonal architecture terms, IRepository would be just a port used in your application layer (i.e. in the command handler), not a layer of its own. I suggest reading up some articles on hexagonal or onion architecture with DDD, e.g.

https://herbertograca.com/2017/11/16/explicit-architecture-01-ddd-hexagonal-onion-clean-cqrs-how-i-put-it-all-together/

Best regards,
Martin

**Comment by RustamGulamov** [comment]
Structure of my projects: Airline.WebApi, Airline.Domain, Airline.Infrastructure. I want to create project Airline.Application for domainService/commandHandler. But Infrastructure is one level up then Airline.Application, right ?
 
Do I understand correctly, сommandHandler should be in Airline.WebApi ?

**Comment by martinzima** [comment]
I am not entirely sure what Airline.Infrastructure contains in your case, but I'd suggest a setup similar to this:

- X.WebApi - API controllers
- X.Messages - commands, queries, possibly also integration events, etc.
- X.Application - command and query handlers
- X.Domain - domain objects (aggregates, entities, etc.)
