### ISSUE TITLE
How can I get snapshot from aggregate ?

### ISSUE THREAD

**Issue by RustamGulamov** [revoframework/Revo#22]
Eventflow can get snapshot from aggregate. https://eventflow.readthedocs.io/Snapshots.html

Revo framework can work with snapshots ?

**Comment by martinzima** [comment]
Hello Rustam,

Revo does not support aggregate snapshots as of this moment, but it is definitely something I had thought about for some time. I have no specific date in the roadmap right now, but I would like to get this feature implemented by the end of Q2 2021.

Regards,
MZ.

**Comment by RustamGulamov** [comment]
Ok, thanks. I will look forward to.

**Comment by martinzima** [comment]
Tracked by #24 now, closing here.
