### ISSUE TITLE
Cannot disable loading module SagasModule.

### ISSUE THREAD

**Issue by RustamGulamov** [revoframework/Revo#27]
SagasModule is always loaded, even if  UseSagas = false;

`
.UseAllEFCoreInfrastructure(x => x.UseSagas = false)
`

It is bug ?

**Comment by martinzima** [comment]
Yes, I can see now that this is indeed a bug. The _advancedAction_ configuration lambda for _UseAllEFCoreInfrastructure_ is never run. I will fix this in the upcoming release. Is this causing any trouble for you now?

**Comment by RustamGulamov** [comment]
Why SagaEventListener has created  ? 


![image](https://user-images.githubusercontent.com/25031460/116218907-aeb2a700-a753-11eb-8538-3e8e174d5e8f.png)

**Comment by martinzima** [comment]
Thanks for the report, I will look into the issue.

For now, if you don't need sagas support, you can completely disable them by using:
```
.ConfigureInfrastructure(
  cfg =>
  {
      cfg.EnableSagas = false;
  })
```
