### ISSUE TITLE
[Question] Can I create read model without tableprefix ?

### ISSUE THREAD

**Issue by RustamGulamov** [revoframework/Revo#30]
Why need tableprefix and ColumnPrefix ? It makes hard to read.

**Comment by RustamGulamov** [comment]
@martinzima

**Comment by martinzima** [comment]
Indeed, this is a certain limitation at this moment stemming from the fact that the internal Revo tables (event store, queues, etc.) have hardcoded names in the SQL migrations files. I'm looking to tackle this limitation in some of the upcoming versions - I guess I will just explicitly specify names for all Revo tables and columns directly in its code (not relying on the conventions), unless I find a more flexible solution.

In the meantime, you can either adopt the naming conventions used by Revo, or you can turn off the conventions and rename its tables (manually or using a migration).
