### ISSUE TITLE
[Question] How can  i to add service from IServiceCollection to kernal ?

### ISSUE THREAD

**Issue by RustamGulamov** [revoframework/Revo#39]
I registred service by DI container asp.net core. ( services.AddScoped<IMyType, MyType>() ).
I added this type to the ctor EFCoreEntityEventToPocoProjector. 
But the kernel is throwing an exception. 
how can you solve?
 Is it possible to solve this problem without binding (IMyType, MyType)  to NinjectModule ?

@martinzima .  Please help

**Comment by martinzima** [comment]
In general, any DI bindings for your application parts should be registered in NinjectModules, the ASP.NET Core DI mechanism is useful only for ASP.NET Core-related stuff. For more info, please see [](https://docs.revoframework.net/reference-guide/dependency-injection).
