### ISSUE TITLE
update to net 8

### ISSUE THREAD

**Issue by ghd258** [revoframework/Revo#67]
update to net 8

**Comment by edprog** [comment]
@martinzima Hello,   I like this framework and would like to use it. Is this still being updated / how long will this be available?

**Comment by martinzima** [comment]
I will look at this in the following days, I suppose the update should be quite painless.

**Comment by martinzima** [comment]
Today I released a new version 1.35.1 that adds build targets for .NET 8.0 and support for EF Core 8.0. Closing this issue.
